add Seed support (#33)
* Improve performance for running payroll process:
- Remove translation for message (this was changed to log with english
language)
- Add cache for agregate functions like SUM, AVG on current running

* Remove unnecessary exception before save order line
Currently exist a validation for price list on any order when a line is
added or modify. The problem is that if you want just add a text for
description or change a account dimension the error is throwed:

```Java
-----------> MOrderLine.save: beforeSave - MOrderLine[1098206, Line=10,
Ordered=8.0000, Delivered=8.0000, Invoiced=8.0000, Reserved=0.0000,
LineNet=22143310.32] [18]
org.adempiere.exceptions.ProductNotOnPriceListException: Product is not
on PriceList - Line No:10, Product:CEMENTO GRIS GENERICO ( SACOS ) ,
Price List:Ventas (VES), Date:02/15/2021
	at org.compiere.model.MOrderLine.beforeSave(MOrderLine.java:923)
	at org.compiere.model.PO.save(PO.java:2170)
	at org.compiere.model.GridTable.dataSavePO(GridTable.java:2192)
	at org.compiere.model.GridTable.dataSave(GridTable.java:1516)
	at org.compiere.model.GridTab.dataSave(GridTab.java:997)
	at org.compiere.apps.APanel.cmd_save(APanel.java:2045)
	at org.compiere.apps.APanel.actionPerformed(APanel.java:1752)
	at org.compiere.apps.AppsAction.actionPerformed(AppsAction.java:286)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)

-----------> GridTable.saveWarning: Error - Product is not on PriceList
- Line No:10, Product:CEMENTO GRIS GENERICO ( SACOS ) , Price
List:Ventas (VES), Date:02/15/2021 [18]
```

* Ignore error when export role from packout
Just add a flag for export role without error when is exported from
packout functionality

* Add the mockito inline mock maker to allow mocking of static methods.

(cherry picked from commit 6c43294539130c13c714e6c175e861784c4b8465)

* Issue #3361 - If the User does not have role access to Desktop or there is no desktop defined, a null pointer exception is caused on log in.  This commit provides a test that fails due to these errors.  The test required a few changes to the DefaultDesktop class to allow mocking of those objects that needed it.  The Mockito inline mock maker extension was also added in the previous commit.

* Issue #3361 - provides a fix for the issue by bailing out of the loop if the user has no data or no role access.

* Add role access to document status indicator
Currently the document status indicator does not make query based on
role access and can show locked record

* Fixed error with wrong XML
Just remove bad step from XML
Fixes: #3372

* Adempiere  #3397 Error of qtyreserved and qtyordered in MProduction (#3398)

https://github.com/adempiere/adempiere/issues/3397

* Add support to axis column based on Value instead id for where clause
This pull request allows create a cross tab based on String values as
columns instead ID.

You can define the follow

|Document No|Value 1|Value2|
|===========|=======|======|
|Test 1|10|35|40|

* Remove unnecessary where clause for sum of Cross data for Smart browse

* Revert "Feature/#3390 rounding problem calculate tax"

* #3403 Adding description when is generate a shipment from Outbound Order https://github.com/adempiere/adempiere/issues/3403 (#3405)

(cherry picked from commit 9ff65f80ff1a50ac06d6f5de95473e382e356865)

* Allows inactive records for ASP packout handler
Just allows export inactive ASP based on packout

* fix #3363: Field length with 0 value. (#3364)

* fix: Field length with 0 values.

* delete vs code ide config.

* remove ide warning into MColumn.

* remove some changes.

Co-authored-by: EdwinBetanc0urt <EdwinBetanco0urt@outlook.com>

* Adempiere B#3421 Fin Report, Parameter Userelement2_ID not  assigned

https://github.com/adempiere/adempiere/issues/3421

* Window Process is displayed on Process List when "Display Logic" is false.

Pull Request: https://github.com/adempiere/adempiere/pull/3404

* Fix distribution by organization dimension (#3414)

Pull request: https://github.com/adempiere/adempiere/pull/3414

* Fixed error with history browse concept

* Add where clause for axis column

* Production Light without batch: error on prepare action 

Pull Request: https://github.com/adempiere/adempiere/pull/3417

* Test for PostgreSQL

* Add And instalation

Co-authored-by: mckayERP <michael.mckay@mckayerp.com>
Co-authored-by: Susanne Calderon <susanne.de.calderon@westfalia-it.com>
Co-authored-by: e-Evolution <victor.perez@e-evolution.com>
Co-authored-by: Edwin Betancourt <EdwinBetanc0urt@outlook.com>
Co-authored-by: EdwinBetanc0urt <EdwinBetanco0urt@outlook.com>
Co-authored-by: Carlos Parada <carlosaparadam@gmail.com>