Fixed error with missing property file for apache ecs packages Just add the file `ecs.properties` is missing after publish packages, this throw a error when you try run a report with html format
The error is showed in terminal like this:

```Shell
java.lang.NoClassDefFoundError: Could not initialize class
org.adempiere.legacy.apache.ecs.ECSDefaults

Cannot find org.adempiere.legacy.apache.ecs.ecs.properties.
```